using Microsoft.CodeAnalysis;
using System.Text;

namespace GeneratePropertyTests.Sources;

/// <summary>
/// 源码文本生成
/// </summary>
public class SourceTextBuilder(StringBuilder builder, int indent = 0)
{
    /// <summary>
    /// 成员处理
    /// </summary>
    public SourceTextBuilder()
        : this(new("// <auto-generated/>\r\n"), 0)
    {
    }
    #region 配置
    private readonly StringBuilder _builder = builder;
    private int _indent = indent;
    #endregion
    /// <summary>
    /// 重写Equals
    /// </summary>
    /// <param name="typeName"></param>
    public void OverrideObjectEquals(string typeName)
    {
        BuildMethod("Equals", "bool", "public", "override");
        AppendLineNoIndent("(object obj)");
        using (Block())
        {
            AppendLine($"return obj is {typeName} other && Equals(other);");
        }
    }
    /// <summary>
    /// 生成判等运算符重载
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="typeName"></param>
    /// <param name="nullCondition"></param>
    public void BuildEqualOperator(string typeName, bool nullCondition)
    {
        AppendLine($"public static bool operator ==({typeName} a, {typeName} b)");
        using (Block())
        {
            if (nullCondition)
                AppendLine("if (a is null) return b is null;");
            AppendLine("return a.Equals(b);");
        }
        AppendLine($"public static bool operator !=({typeName} a, {typeName} b)");
        using (Block())
        {
            AppendLine("return !(a == b);");
        }
    }
    #region Build
    /// <summary>
    /// 定义类型
    /// </summary>
    /// <param name="typeKind"></param>
    /// <param name="typeName"></param>
    /// <param name="modifiers"></param>
    public void BuildType(string typeKind, string typeName, params string[] modifiers)
    {
        var builder = GenerateIndent();
        BuildModifiers(builder, modifiers);
        builder.Append($"{typeKind} {typeName}");
    }
    /// <summary>
    /// 定义方法
    /// </summary>
    /// <param name="method"></param>
    /// <param name="methodType"></param>
    /// <param name="modifiers"></param>
    public void BuildMethod(string method, string methodType, params IEnumerable<string> modifiers)
    {
        var builder = GenerateIndent();
        BuildModifiers(builder, modifiers);
        builder.Append($"{methodType} {method}");
    }
    /// <summary>
    /// 定义构造函数
    /// </summary>
    /// <param name="name"></param>
    /// <param name="modifiers"></param>
    public void BuildConstructor(string name, params IEnumerable<string> modifiers)
    {
        var builder = GenerateIndent();
        BuildModifiers(builder, modifiers);
        builder.Append(name);
    }
    /// <summary>
    /// 定义字段
    /// </summary>
    /// <param name="name"></param>
    /// <param name="valueType"></param>
    /// <returns></returns>
    public void BuildField(string name, string valueType, params string[] modifiers)
    {
        var builder = GenerateIndent();
        BuildModifiers(builder, modifiers);
        builder.AppendLine($"{valueType} {name};");
    }
    /// <summary>
    /// 按字段定义属性
    /// </summary>
    /// <param name="propertyName"></param>
    /// <param name="valueType"></param>
    /// <param name="argumentName"></param>
    /// <param name="writeAcessor"></param>
    public void BuildPropertyByArgument(string propertyName, string valueType, string argumentName, string writeAcessor = "set")
    {
        var builder = GenerateIndent();
        BuildModifiers(builder, "public");
        builder.AppendLine($"{valueType} {propertyName}");
        using (Block())
        {
            AppendLine($"get => _{argumentName};");
            if (!string.IsNullOrEmpty(writeAcessor))
                AppendLine($"{writeAcessor} => _{argumentName} = {argumentName};");
        }
    }
    /// <summary>
    /// 按访问器定义属性
    /// </summary>
    /// <param name="propertyName"></param>
    /// <param name="valueType"></param>
    /// <param name="accessors"></param>
    public void BuildPropertyByAccessor(string propertyName, string valueType, params string[] accessors)
    {
        var builder = GenerateIndent();
        BuildModifiers(builder, "public");
        builder.Append(valueType).Append(' ').Append(propertyName).Append(' ').Append('{');
        foreach (var item in accessors)
        {
            builder.Append(' ').Append(item).Append(';');
        }
        builder.Append(' ').Append('}').AppendLine();
    }
    #endregion
    /// <summary>
    /// 添加一行
    /// </summary>
    public void AppendLine(string value)
    {
        GenerateIndent()
            .AppendLine(value);
    }
    /// <summary>
    /// 添加一行(无缩进)
    /// </summary>
    /// <param name="value"></param>
    public void AppendLineNoIndent(string value)
    {
        _builder.AppendLine(value);
    }
    /// <summary>
    /// 添加注释
    /// </summary>
    /// <param name="summarys"></param>
    public void BuildSummary(params IEnumerable<string> summarys)
    {
        AppendLine("/// <summary>");
        foreach (var summary in summarys)
        {
            AppendLine($"/// {summary}");
        }
        AppendLine("/// </summary>");
    }
    #region BuildNamespace
    ///// <summary>
    ///// 定义命名空间
    ///// </summary>
    ///// <param name="namedTypeSymbol"></param>
    //public void BuildNamespace(INamedTypeSymbol namedTypeSymbol)
    //{
    //    string ns = namedTypeSymbol.ContainingNamespace.ToDisplayString();
    //    BuildNamespace(ns);
    //}
    ///// <summary>
    ///// 定义命名空间
    ///// </summary>
    ///// <param name="ns"></param>
    //public void BuildNamespace(string ns)
    //{
    //    AppendLine($"namespace {ns}");
    //}
    ///// <summary>
    ///// 定义命名空间
    ///// </summary>
    ///// <param name="ns"></param>
    //public void BuildNamespace(INamespaceSymbol ns)
    //    => BuildNamespace(ns.ToDisplayString());
    /// <summary>
    /// 代码段开始(花括号)
    /// </summary>
    public void BuildBeigin()
    {
        BuildBeigin(_builder, ref _indent);
    }
    /// <summary>
    /// 代码段结束(花括号)
    /// </summary>
    public void BuildEnd()
    {
        BuildEnd(_builder, ref _indent);
    }
    /// <summary>
    /// 缩进
    /// </summary>
    /// <param name="builder"></param>
    /// <returns></returns>
    public StringBuilder GenerateIndent()
    {
        return BuildIndent(_builder, _indent);
    }
    /// <summary>
    /// 添加修饰符
    /// </summary>
    /// <param name="modifiers"></param>
    /// <returns></returns>
    public StringBuilder BuildModifiers(params IEnumerable<string> modifiers)
    {
        return BuildModifiers(_builder, modifiers);
    }
    #endregion
    #region Build
    /// <summary>
    /// 代码段开始(花括号)
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="indent">缩进数量</param>
    public static void BuildBeigin(StringBuilder builder, ref int indent)
    {
        BuildIndent(builder, indent)
            .AppendLine("{");
        indent += 4;
    }
    /// <summary>
    /// 代码段结束(花括号)
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="indent">缩进数量</param>
    public static void BuildEnd(StringBuilder builder, ref int indent)
    {
        indent -= 4;
        BuildIndent(builder, indent)
            .AppendLine("}");        
    }
    /// <summary>
    /// 缩进
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="indent"></param>
    /// <returns></returns>
    public static StringBuilder BuildIndent(StringBuilder builder, int indent)
    {
        if (indent > 0)
            builder.Append(' ', indent);
        return builder;
    }
    /// <summary>
    /// 添加修饰符
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="modifiers"></param>
    /// <returns></returns>
    public static StringBuilder BuildModifiers(StringBuilder builder, params IEnumerable<string> modifiers)
    {
        foreach (string modifier in modifiers)
        {
            builder.Append(modifier)
                .Append(' ');
        }
        return builder;
    }
    #endregion
    #region Scope
    /// <summary>
    /// 代码块
    /// </summary>
    /// <returns></returns>
    public BlockScope Block()
        => new(this);
    /// <summary>
    /// 命名空间
    /// </summary>
    /// <param name="ns"></param>
    /// <returns></returns>
    public BlockScope NameSpace(INamespaceSymbol ns)
        => NameSpace(ns.ToDisplayString());
    /// <summary>
    /// 命名空间
    /// </summary>
    /// <param name="ns"></param>
    /// <returns></returns>
    public BlockScope NameSpace(string ns)
    {
        AppendLine($"namespace {ns}");
        return new(this);
    }
    /// <summary>
    /// 锁代码块
    /// </summary>
    /// <param name="name"></param>
    /// <returns></returns>
    public BlockScope Lock(string name)
    {
        AppendLine($"lock({name})");
        return new(this);
    }
    /// <summary>
    /// 
    /// </summary>
    /// <param name="name"></param>
    /// <param name="statement"></param>
    /// <returns></returns>
    public BlockScope Using(string name, string statement)
    {
        AppendLine($"using(var {name} = {statement})");
        return new(this);
    }
    #endregion
    /// <summary>
    /// 拼接全部字符
    /// </summary>
    /// <returns></returns>
    public override string ToString()
        => _builder.ToString();
}
