using Hand;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SyntaxScriptingTests;

public class HelloGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 查找需要生成的类
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax type && type.Modifiers.IsPartial(),
            transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node);
        // 注册输出逻辑
        context.RegisterImplementationSourceOutput(provider, Execute);
    }
    /// <summary>
    /// 执行
    /// </summary>
    /// <param name="sourceContext"></param>
    /// <param name="generatorContext"></param>
    void Execute(SourceProductionContext sourceContext, ClassDeclarationSyntax type)
    {
        var ns = GetNamespace(type);
        var typeName = type.Identifier.ValueText;
        string source = @$"""// <auto-generated/>
using System;

{(string.IsNullOrWhiteSpace(ns) ? "" : $"namespace {ns};")}

partial class {ns}
{{
    public static void Hello(string name) =>
        Console.WriteLine($""Hello: '{{name}}'"");
}}
""";

        var sourceText = SourceText.From(source, Encoding.UTF8);
        sourceContext.AddSource($"{typeName}.g.cs", sourceText);
    }
    
    public static string GetNamespace(TypeDeclarationSyntax type)
    {
        if(type.Parent is BaseNamespaceDeclarationSyntax ns)
            return ns.ToFullString();
        return string.Empty;
    }
}