using Hand;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace EasySyntaxTests;

public class BuilderTests
{
    [Fact]
    public void BySyntaxTree()
    {
        var type = SyntaxFactory.ClassDeclaration("UserId")
            .Public()
            .Partial();
        var original = SyntaxFactory.IdentifierName("original");
        var _original = SyntaxFactory.IdentifierName("_original");
        var field = SyntaxGenerator.IntType.Field(_original.Identifier)
            .Private()
            .ReadOnly();
        var property = SyntaxGenerator.IntType.GetOnlyProperty("Original", _original)
            .Public();

        var constructor = type.Constructor(SyntaxGenerator.IntType.Parameter(original.Identifier))
            .Public()
            .ToBuilder()
            .Add(_original.Assign(original))
            .End();

        var builder = SyntaxGenerator.Create("Models", type, constructor, field, property);
        var result = builder.Build();
        Assert.NotEmpty(result.ToFullString());
    }
    [Fact]
    public void ListParameters()
    {
        var original = SyntaxFactory.IdentifierName("original");
        var _original = SyntaxFactory.IdentifierName("_original");
        var field = SyntaxGenerator.IntType.Field(_original.Identifier, original)
            .Private()
            .ReadOnly();
        var property = SyntaxGenerator.IntType.GetOnlyProperty("Original", _original)
            .Public();
        var type = SyntaxFactory.ClassDeclaration("UserId")
            .Public()
            .Partial()
            .AddParameterListParameters(SyntaxGenerator.IntType.Parameter(original.Identifier));
        var builder = SyntaxGenerator.Create("Models", type, field, property);
        var result = builder.Build();
        Assert.NotEmpty(result.ToFullString());        
    }
    [Fact]
    public void ListParameterForProperty()
    {
        var original = SyntaxFactory.IdentifierName("original");
        var property = SyntaxGenerator.IntType.GetOnlyProperty("Original", original)
            .Public();
        var type = SyntaxFactory.ClassDeclaration("UserId")
            .Public()
            .Partial()
            .AddParameterListParameters(SyntaxGenerator.IntType.Parameter(original.Identifier));
        var builder = SyntaxGenerator.Create("Models", type, property);
        var result = builder.Build();
        Assert.NotEmpty(result.ToFullString());
    }
    [Fact]
    public void ListParameterForRecord()
    {
        var type = SyntaxGenerator.RecordStructDeclaration("UserId")
            .Public()
            .Partial()
            .AddParameterListParameters(SyntaxGenerator.IntType.Parameter("Original"))
            .WithSemicolonToken();
        var builder = SyntaxGenerator.Create("Models", type);
        var result = builder.Build();
        Assert.NotEmpty(result.ToFullString());
    }
    [Fact]
    public void Declaration()
    {
        // 参考: https://code-maze.com/csharp-source-generators/
        const string className = "UserId";
        var originalType = SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.IntKeyword));
        var declaration = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.IdentifierName("Models"))
            .WithLeadingTrivia(SyntaxFactory.TriviaList(
                SyntaxFactory.Comment("// <auto-generated/>")
            ))
            .AddMembers(
                SyntaxFactory.ClassDeclaration(className)
                .AddModifiers(
                    SyntaxFactory.Token(SyntaxKind.PublicKeyword)
                )
                .AddMembers(
                    SyntaxFactory.FieldDeclaration(SyntaxFactory.VariableDeclaration(originalType))
                        .AddDeclarationVariables(
                            SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("_original"))
                        )
                    .AddModifiers(
                        SyntaxFactory.Token(SyntaxKind.PrivateKeyword),
                        SyntaxFactory.Token(SyntaxKind.ReadOnlyKeyword)
                    ),
                    SyntaxFactory.PropertyDeclaration(
                        originalType,
                        SyntaxFactory.Identifier("Original")
                    )
                    .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                    .AddAccessorListAccessors(
                        SyntaxFactory.AccessorDeclaration(
                            SyntaxKind.GetAccessorDeclaration
                        )
                        .WithBody(
                            SyntaxFactory.Block(
                                SyntaxFactory.ReturnStatement(SyntaxFactory.IdentifierName("_original"))
                            )
                        )
                    ),
                    SyntaxFactory.ConstructorDeclaration(className)
                        .AddModifiers(
                            SyntaxFactory.Token(SyntaxKind.PublicKeyword)
                        )
                        .AddParameterListParameters(
                            SyntaxFactory.Parameter(SyntaxFactory.Identifier("original")).WithType(originalType)
                        )
                        .WithBody(
                            SyntaxFactory.Block(
                                SyntaxFactory.ExpressionStatement(
                                    SyntaxFactory.AssignmentExpression(SyntaxKind.SimpleAssignmentExpression, SyntaxFactory.IdentifierName("_original"), SyntaxFactory.IdentifierName("original"))
                                )
                            )
                        )
                )
            ).NormalizeWhitespace();
        var code = declaration.ToFullString();
        Assert.NotEmpty(code);
        var literal = SyntaxFactory.LiteralExpression(SyntaxKind.NumericLiteralExpression, SyntaxFactory.Literal(1UL))
            .NormalizeWhitespace()
            .ToFullString();
        Assert.NotEmpty(literal);
    }
    [Fact]
    public void CreateRecord()
    {
        var record = SyntaxFactory.RecordDeclaration(SyntaxFactory.Token(SyntaxKind.RecordKeyword), "Person")
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddParameterListParameters(
                SyntaxFactory.Parameter(SyntaxFactory.Identifier("Name")).WithType(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.StringKeyword)))
            )
            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken));
        // 将记录声明转换为字符串查看结果
        var tree = SyntaxFactory.CompilationUnit()
            .AddMembers(record);
        var code = tree.NormalizeWhitespace().ToFullString();
        Console.WriteLine(code);
    }
    [Fact]
    public void CreateStructRecord()
    {
        var recordDeclaration = SyntaxFactory.RecordDeclaration(SyntaxKind.RecordStructDeclaration, SyntaxFactory.Token(SyntaxKind.RecordKeyword), SyntaxFactory.Identifier("UserId"))
            .WithClassOrStructKeyword(SyntaxFactory.Token(SyntaxKind.StructKeyword))
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddParameterListParameters(
                SyntaxFactory.Parameter(SyntaxFactory.Identifier("Id")).WithType(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.IntKeyword)))
            )            
            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken));
        // 将记录声明转换为字符串查看结果
        var tree = SyntaxFactory.CompilationUnit()
            .AddMembers(recordDeclaration);
        var code = tree.NormalizeWhitespace().ToFullString();
        Console.WriteLine(code);
    }
    [Fact]
    public void CreateStructRecordBySyntaxTree()
    {
        var recordDeclaration = SyntaxGenerator.RecordStructDeclaration("Person")
            .Public()
            .AddParameterListParameters(
                SyntaxGenerator.StringType.Parameter("Name")
            )
            .WithSemicolonToken();
        // 将记录声明转换为字符串查看结果
        var tree = SyntaxFactory.CompilationUnit()
            .AddMembers(recordDeclaration);
        var code = tree.NormalizeWhitespace().ToFullString();
        Console.WriteLine(code);
    }
}
