using Hand;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EasySyntaxTests;

public class SourceTextTest
{
    [Fact]
    public void ParseText()
    {
        string sourceText = @"
// <auto-generated/>
class User
{
    public string Name { get; set; }
}";
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(sourceText);
        Assert.NotNull(syntaxTree);
        var typeDeclaration = syntaxTree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>().FirstOrDefault();
        Assert.NotNull(typeDeclaration);
    }
    [Fact]
    public void Const()
    {
        string sourceText = @"
    // <auto-generated/>
    class User
    {
        const int o = 1;
    }";
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(sourceText);
        Assert.NotNull(syntaxTree);
        var typeDeclaration = syntaxTree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>().FirstOrDefault();
        Assert.NotNull(typeDeclaration);
    }
    [Fact]
    public void Var()
    {
        string sourceText = @"
    // <auto-generated/>
    var c = 1";
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(sourceText);
        Assert.NotNull(syntaxTree);
        var typeDeclaration = syntaxTree.GetRoot().DescendantNodes().OfType<VariableDeclarationSyntax>().FirstOrDefault();
        Assert.NotNull(typeDeclaration);
        var c = SyntaxGenerator.VarType.Variable("c", SyntaxGenerator.Literal(1));
        Assert.NotNull(c);
    }

    [Fact]
    public void StructRecord()
    {
        // 创建一个简单的表达式：Console.WriteLine("Hello, World!");
        var owner = SyntaxFactory.IdentifierName("Console");
        var methodName = SyntaxFactory.IdentifierName("WriteLine");
        var argument = SyntaxFactory.Argument(SyntaxFactory.ParseExpression("\"Hello, World!\""));
        var invocationExpression = SyntaxFactory.InvocationExpression(SyntaxFactory.QualifiedName(owner, methodName), SyntaxFactory.ArgumentList(SyntaxFactory.SingletonSeparatedList(argument)));
        //SyntaxFactory.QualifiedName(owner, methodName);
        // 将表达式添加到语句中
        var statement = SyntaxFactory.ExpressionStatement(invocationExpression);
        var globalStatement = SyntaxFactory.GlobalStatement(statement);

        // 输出看看结果
        Console.WriteLine(globalStatement.ToFullString()); // 输出：Console.WriteLine("Hello, World!");
        string sourceText = "public record struct User(string Name);";
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(sourceText);
        Assert.NotNull(syntaxTree);
        var typeDeclaration = syntaxTree.GetRoot().DescendantNodes().OfType<RecordDeclarationSyntax>().FirstOrDefault();
        Assert.NotNull(typeDeclaration);
    }

    [Fact]
    public void ToFullString()
    {
        var userType = SyntaxFactory.ClassDeclaration("User")
            .WithLeadingTrivia(SyntaxFactory.TriviaList(
                SyntaxFactory.Comment("// <auto-generated/>")
            ))
            .AddMembers(
                SyntaxFactory.PropertyDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.StringKeyword)), "Name")
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                .AddAccessorListAccessors(
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)),
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
                )
            );

        string sourceText = userType.NormalizeWhitespace().ToFullString();
        Assert.NotNull(sourceText);
    }
    
    [Fact]
    public void WithLeadingTrivia()
    {
        var property = SyntaxFactory.PropertyDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.StringKeyword)), "Name")
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                .WithLeadingTrivia(
                    //SyntaxFactory.Whitespace(" "),
                    SyntaxFactory.Trivia(
                        SyntaxFactory.DocumentationComment(
                            SyntaxFactory.XmlSummaryElement(
                                //NewLineAndLineStart(),
                                SyntaxFactory.XmlText("用户名")
                                //NewLineAndLineStart()
                            )
                        )
                    )
                )
                .WithTrailingTrivia(SyntaxFactory.CarriageReturnLineFeed)
                .AddAccessorListAccessors(
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)),
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
                );
        var userType = SyntaxFactory.ClassDeclaration("User")
            .WithLeadingTrivia(SyntaxFactory.TriviaList(
                SyntaxFactory.Comment("// <auto-generated/>")
            ))
            .AddMembers(property);

        string sourceText = userType.NormalizeWhitespace().ToFullString();
        Assert.NotNull(sourceText);
    }
    private static SyntaxToken NewLineLiteral()
    {
        return SyntaxFactory.XmlTextNewLine(SyntaxFactory.TriviaList(), Environment.NewLine, Environment.NewLine, SyntaxFactory.TriviaList());
    }
    private static SyntaxToken LineStartLiteral()
    {
        return SyntaxFactory.XmlTextLiteral(SyntaxFactory.TriviaList(SyntaxFactory.DocumentationCommentExterior("///")), " ", " ", SyntaxFactory.TriviaList());
    }
    //private static XmlNodeSyntax NewLineAndLineStart()
    //{
    //    return SyntaxFactory.XmlText(NewLineLiteral(), LineStartLiteral());
    //}
    [Fact]
    public void CompileClass()
    {
        string sourceText = @"
class User
{
    public string Name { get; set; }
}";
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(sourceText);
        var compilation = CSharpCompilation.Create("Tests", [syntaxTree]);
        INamedTypeSymbol? userSymbol = compilation.GetTypeByMetadataName("User");
        Assert.NotNull(userSymbol);
    }
    [Fact]
    public void CompileRecord()
    {
        string sourceText = "public record User(string Name);";
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(sourceText);
        var compilation = CSharpCompilation.Create("Tests", [syntaxTree]);
        INamedTypeSymbol? userSymbol = compilation.GetTypeByMetadataName("User");
        Assert.NotNull(userSymbol);
    }
}

