<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\package.props" />
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Nullable>enable</Nullable>
		<Version>$(VersionBase).0-alpha</Version>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<IsRoslynComponent>true</IsRoslynComponent>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<LangVersion>Latest</LangVersion>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<NoWarn>$(NoWarn);NU5128</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0">
			<IncludeAssets>compile; analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0">
			<IncludeAssets>compile; analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Hand.Core" Version="0.3.2.5-alpha">
			<IncludeAssets>compile; analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Hand.AutoCache" Version="0.3.2.1-alpha">
			<IncludeAssets>compile; analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Hand.MemberValidation" Version="0.3.2.2-alpha">
			<IncludeAssets>compile; analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Hand.Validation" Version="0.3.2.2-alpha">
			<IncludeAssets>compile; analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
		<PackageReference Include="System.Memory" Version="4.6.3">
			<IncludeAssets>compile;analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Hand.Naming" Version="0.3.2.1-alpha">
			<IncludeAssets>compile; analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Hand.Generators.Generators\Hand.Generators.Generators.csproj">
			<IncludeAssets>compile;analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</ProjectReference>
		<ProjectReference Include="..\Hand.Generators.Naming\Hand.Generators.Naming.csproj">
			<IncludeAssets>compile;analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</ProjectReference>
		<ProjectReference Include="..\Hand.Generators.Reflection\Hand.Generators.Reflection.csproj">
			<IncludeAssets>compile;analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</ProjectReference>
		<ProjectReference Include="..\Hand.Generators.EasySyntax\Hand.Generators.EasySyntax.csproj">
			<IncludeAssets>compile;analyzers</IncludeAssets>
			<PrivateAssets>compile</PrivateAssets>
		</ProjectReference>
		<ProjectReference Include="..\Hand.Generators.Attributes\Hand.Generators.Attributes.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>
</Project>
