using Hand.Members;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Runtime.CompilerServices;

namespace Hand;

/// <summary>
/// 注释扩展方法
/// </summary>
public static partial class GenerateServices
{
    /// <summary>
    /// 获取文档注释
    /// </summary>
    /// <param name="node"></param>
    /// <returns></returns>
    public static DocumentationCommentTriviaSyntax? GetDocumentation(this CSharpSyntaxNode node)
    {
        foreach (var trivia in node.GetLeadingTrivia())
        {
            if (trivia.HasStructure && trivia.GetStructure() is DocumentationCommentTriviaSyntax documentation)
                return documentation;
        }
        return null;
    }
    /// <summary>
    /// 获取摘要注释
    /// </summary>
    /// <param name="documentation"></param>
    /// <returns></returns>
    public static XmlElementSyntax? GetSummary(this DocumentationCommentTriviaSyntax documentation)
    {
        foreach (var item in documentation.Content)
        {
            if (item is XmlElementSyntax xmlElement && xmlElement.StartTag.Name.LocalName.ValueText == "summary")
                return xmlElement;
        }
        return null;
    }
    /// <summary>
    /// 获取摘要注释
    /// </summary>
    /// <param name="node"></param>
    /// <returns></returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static XmlElementSyntax? GetSummary(this CSharpSyntaxNode node)
        => GetDocumentation(node)?
        .GetSummary();
    /// <summary>
    /// 增加auto-generated注释
    /// </summary>
    /// <param name="unit"></param>
    /// <returns></returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static CompilationUnitSyntax WithGenerated(this CompilationUnitSyntax unit)
        => unit.WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Comment("// <auto-generated/>\r\n")));
    /// <summary>
    /// 增加摘要注释
    /// </summary>
    /// <typeparam name="TMember"></typeparam>
    /// <param name="member"></param>
    /// <param name="lines"></param>
    /// <returns></returns>
    public static TMember WithSummary<TMember>(this TMember member, params string[] lines)
        where TMember : SyntaxNode
    {
        var documentation = SyntaxGenerator.CreateDocumentation(lines);
        if (documentation is null)
            return member;
        return member.WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Trivia(documentation)));
    }
    /// <summary>
    /// 增加摘要注释
    /// </summary>
    /// <typeparam name="TMember"></typeparam>
    /// <param name="member"></param>
    /// <param name="summary"></param>
    /// <returns></returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TMember WithSummary<TMember>(this TMember member, XmlElementSyntax summary)
        where TMember : SyntaxNode
        => member.WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Trivia(SyntaxGenerator.CreateDocumentation(summary))));
    /// <summary>
    /// 增加摘要注释
    /// </summary>
    /// <typeparam name="TMember"></typeparam>
    /// <param name="member"></param>
    /// <param name="documentation"></param>
    /// <returns></returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TMember WithDocumentation<TMember>(this TMember member, DocumentationCommentTriviaSyntax documentation)
        where TMember : SyntaxNode
        => member.WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Trivia(documentation)));
    /// <summary>
    /// 增加注释
    /// </summary>
    /// <typeparam name="TMember"></typeparam>
    /// <param name = "member"></param>
    /// <param name = "comment"></param>
    /// <returns></returns>
    public static TMember WithComment<TMember>(this TMember member, Comment comment)
        where TMember : SyntaxNode
    {
        var documentation = SyntaxGenerator.CreateDocumentation(comment);
        if (documentation is null)
            return member;
        return member.WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Trivia(documentation)));
    }
}
