using Hand;
using Hand.Mapping;

namespace GenerateConvertTests;

public class ConvertTests
{
    [Fact]
    public void ToUser()
    {
        var source = @"
using Hand;
using Hand.Mapping;
using Hand.Models;

namespace GenerateConvertTests;

public record User(int Id, string Name);

[GenerateConvert<User>]
public partial record UserDto(int Id, string Name);
";
        var driver = SyntaxTreeDriver.CreateDefaultDriver()
            .Reference(typeof(GenerateConvertAttribute<>));
        var result = driver.Generate<ConvertGenerator>(source)
            .GetRunResult();
        var syntaxTree = result.GeneratedTrees.FirstOrDefault();
        Assert.NotNull(syntaxTree);
        var code = syntaxTree.GetText().ToString();
        Assert.Contains("ToUser", code);
    }
    [Fact]
    public void NoPartial()
    {
        var source = @"
using Hand;
using Hand.Mapping;
using Hand.Models;

namespace GenerateConvertTests;

public record User(int Id, string Name);

[GenerateConvert<User>(ConvertFrom = true)]
public record UserDto(int Id, string Name);
";
        var driver = SyntaxTreeDriver.CreateDefaultDriver()
            .Reference(typeof(GenerateConvertAttribute<>));
        var result = driver.Generate<ConvertGenerator>(source)
            .GetRunResult();
        var syntaxTree = result.GeneratedTrees.FirstOrDefault();
        Assert.NotNull(syntaxTree);
        var code = syntaxTree.GetText().ToString();
        Assert.Contains("ToUser", code);
    }
    [Fact]
    public void ToUserWithMaster()
    {
        var source = @"
using Hand;
using Hand.Mapping;
using Hand.Models;
using System.Collections.Generic;

namespace GenerateConvertTests;

public record User(int Id, string Name, User Master, User[] Followers);

[GenerateConvert<User>]
public partial record UserDto(int Id, string Name, UserDto Master, List<UserDto> Followers);
";
        var driver = SyntaxTreeDriver.CreateDefaultDriver()
            .Reference(typeof(GenerateConvertAttribute<>));
        var result = driver.Generate<ConvertGenerator>(source)
            .GetRunResult();
        var syntaxTree = result.GeneratedTrees.FirstOrDefault();
        Assert.NotNull(syntaxTree);
        var code = syntaxTree.GetText().ToString();
        Assert.Contains("ToUser", code);
    }
}
//// <auto-generated/>
//namespace GenerateConvertTests;

//partial record UserDto
//{
//    ///<summary>
//    ///转化为User
//    ///</summary>
//    public GenerateConvertTests.User ToUser() => new(Id, Name, Master.ToUser(), System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Select(Followers, item => item.ToUser())));
//}
